apiVersion: apps/v1
kind: Deployment
metadata:
  name: spot-tolerant-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spot-tolerant
  template:
    metadata:
      labels:
        app: spot-tolerant
    spec:
      nodeSelector:
        lifecycle: spot
      tolerations:
      - key: "lifecycle"
        operator: "Equal"
        value: "spot"
        effect: "NoSchedule"
      containers:
      - name: nginx
        image: nginx:alpine
